version: 2.1
jobs:
  build:
    docker:
      - image:tqhuy1996developer/nodejs
    steps:
      - checkout
      - run:
        name: install dependency
        command: |
          echo 'npm install dependency'
      - run:
        name: build docker
        command: |
          echo 'build docker'