version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: npm install dependency
          command: |
            npm install
      - setup_remote_docker
      - run:
          name: run test
          command: |
            npm install mocha
            npm test
      - run:
          name: build and push docker
          command: |
            docker build . -t tqhuy1996developer/nodejs
            docker login -u tqhuy1996developer -p Husky@0946515847
            docker push tqhuy1996developer/nodejs
            