version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: npm install dependency
          command: |
            npm install
      - run:
          name: build docker
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
