version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: npm install dependency
          command: |
            echo 'npm install'
      - run:
          name: build docker
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
